### PR TITLE
feat: support com.oasisfeng.island

### PR DESCRIPTION
**Pull request by andy-math**

### CODE REVIEW

**Comment by aistra0528** [comment]
感谢你的贡献😄

**Comment by TheDcoder** [comment]
How does this work? Does it require mainland support? I tried it in with Insular work profile but it does not work, tried both the `Hide` and `Suspend` modes of the `Island` working method :confused:

**Comment by andy-math** [comment]
@TheDcoder I tested it on Island mainland. The current Hail doesn't have the feature across profiles for now, so if you want to freeze in work profile, you may need to install Hail in the work profile. Also I'm not sure how much difference there is between Insular and Island, perhaps more adaptations will have to be made for Insular.

**Comment by TheDcoder** [comment]
@andy-math I tried it with Hail installed in the work profile, not in the main profile. It can see the apps but it can't freeze them.

Besides... can we expect to see work profile support in Hail? I would really like to use it but work profile support is also important because I like to separate some apps from my main apps.

**Comment by andy-math** [comment]
@TheDcoder I'll work on that. Please wait some time.

**Comment by TheDcoder** [comment]
That is great news, thank you so much! I really liked your "Remove Device Owner" feature, it saved me from wiping my phone to just try different manager apps :smile:

**Comment by andy-math** [comment]
@TheDcoder I tried using the freeze feature in the work profile and everything seems to be working fine. If it doesn't freeze on the first try, it's possible that this is because Hail is requesting Island permissions and needs to select the work profile to Island mode again. This is affected by Hail's internal authorization process, and I have no plans to make a change until Hail's authorization process is changed.
On the other hand, the OEM system also affects how Island works, the system I tested was ZTE MyOS 13 (Android 13) on the nubia Z40S Pro.
If you need more help, perhaps you need to provide more detailed information such as logcat for diagnosis.
WX20231104-020021

**Comment by andy-math** [comment]
@TheDcoder Additionally, Hail's Island mode must be granted these two permissions (depending on the working mode you use)
WechatIMG213

**Comment by TheDcoder** [comment]
@andy-math I'm on Google Pixel 6a so the Android should be very vanilla. I tried Hail in the work profile again but still no success...

I checked the permissions and I only see a single permission related to Island, don't see the sub-permissions:


By the way, did you create a work profile with Hail active as device owner? If so, how did you do that?

**Comment by andy-math** [comment]
@TheDcoder It looks like you've given Hail permission to control Island. According to Island's instructions, Hail's (or any other app's) device owner mode will be incompatible with the work profile, which is why Island uses managed profile instead of device owner mode. Island manages both mainland and work profiles when I tested it, what are your mainland and work profiles like? I'm afraid I'm not in a position to test if your mainland is managed using other software...

**Comment by TheDcoder** [comment]
@andy-math Currently I don't have any device owner, only a managed profile (work profile) controlled by Island (Insular) and Hail is installed within this managed work profile, so these apps don't have any control over the main profile.

By the way, Island/Insular supports managed mainland (device owner) as well as managed profile (work profile) **at the same time**, according to the [instructions](https://secure-system.gitlab.io/Insular/setup.html#Insularactivate-managed-mainland) you first need to setup work profile and then you manually grant Island "mainland" access by setting it as the device owner.

I don't have this setup, but it is worth mentioning because we can potentially activate Hail as device admin after setting up another work profile admin app. I'm planning to try this with Hail and Shelter soon.

**Comment by andy-math** [comment]
@TheDcoder You're right, work profiles can indeed coexist with device owners, except that such coexistence requires adherence to a strict order of precedence when setting them up. Earlier Island also used device owner to provide managed mainland, later this feature was deprecated and moved to the current managed profile. from this point of view, Insular looks like an earlier Island fork, I'm not sure if it follows Island support api v2, or if it only supports api v1. I'll check it out.

**Comment by TheDcoder** [comment]
@andy-math Insular seems to be based on Island 6.0.5 as it's the last [commit](https://gitlab.com/secure-system/Insular/-/commit/f2d7f1cd92d222a5ab13aca99ee48d487463f173) by OasisFeng in the active branch of their repository.

Incidentally I also looked into the [API of Insular](https://gitlab.com/secure-system/Insular/-/blob/1733c7cc3ac382dca80712b11230f7243c35fd2f/shared/src/main/java/com/oasisfeng/island/api/Api.java) a few weeks ago, it's the v2.1 version:

```
* <p>API revisions:
* <ul>
* <li>v1.0 released in Island v2.0.
* <li>v1.1 released in Island v2.5 (250).
* <li>v2.0 released in Island v2.9 (29000).
* <li>v2.1 released in Island v3.5.1 (35100).
* </ul>
```

It's the same as [Island's API](https://github.com/oasisfeng/island/blob/0a916eac0610a7faf6e57b805b1942ad713c46cd/shared/src/main/java/com/oasisfeng/island/api/Api.java).

**Comment by andy-math** [comment]
@TheDcoder I think I know why. Insular's package name is "com.oasisfeng.island.fdroid" but Hail sends the request to package "com.oasisfeng.island". it. Considering that Hail doesn't currently have a detailed settings interface for each work mode, and that Insular is not a very popular fork of Island, I'm not going to make adjustments to the current Island support for the time being.

Some possible approaches:
1. Compile and use Hail with "com.oasisfeng.island.fdroid" instead of "com.oasisfeng.island".
2. Compile and install Insular using "com.oasisfeng.island" as the package name.

For Open Api applications, it would be a good idea to develop a secondary menu to select which package it sends requests to. You might consider opening an issue.

I'll look into whether there's a way to auto-detect the current profile manager package name, but for a setup like this, it doesn't seem like a good idea to rely on auto-discovery as opposed to manual specification.

**Comment by TheDcoder** [comment]
@andy-math Is it not possible to simply check if a package is installed? If so, you can do a one-time check for `com.oasisfeng.island` and then fallback to `com.oasisfeng.island.fdroid`. It doesn't really matter IMO because it's a minor edge-case thing, we don't need such hacks often.

**Comment by andy-math** [comment]
@TheDcoder This approach is incorrect. Considering that a profile may have both Island and Insular installed, and a user may switch the manager of this profile midway, the mechanism provided by Hail should not let such a few users get stuck in a bug.

**Comment by TheDcoder** [comment]
@andy-math Actually it's not possible to switch the profile manager without erasing the entire profile :sweat_smile: 

And you don't need to save the detected package to storage, just store it in memory and recheck on startup.

**Comment by andy-math** [comment]
@TheDcoder So, how can I determine which of the two apps installed at the same time is the activated manager?

**Comment by TheDcoder** [comment]
@andy-math The neat part is, we don't :wink: 

At-least that's what I envisioned, no one is crazy enough to have both apps installed... so let's just assume that if island is installed, it's the activated manager. Otherwise just fall back to Insular.

The solution is simple and works for 99.9999% of the users, so no harm done in saving a lot of effort just to save the miniscule amount of people who have both installed but only insular activated... it will start working as soon as they uninstall the island app.

**Comment by andy-math** [comment]
@TheDcoder check this: https://github.com/aistra0528/Hail/pull/149

**Pull request merged**
