### PR TITLE
Auto freeze only configured tags?

### PR DESCRIPTION
**Pull request by juanitobananas**
Hi @aistra0528,

First of all, thank you very much for this cool app!! :clap::clap::clap: 

Would you be willing to merge an option to only auto-freeze certain tags?
I've already started working on it :smile: This is still very much a **WIP**..

If you're interested, I'll try to finish it and polish it a little. If not, I'll keep a not-so-nice fork for myself :wink:

#### Working for now

- New setting to choose which tags should be frozen.
- Auto freeze ignores the tags which aren't selected.

#### Yet to do

- It would be nice not to start the auto-freeze service at all (so that the notification isn't shown) if the launched apps aren't supposed to be frozen. I still have to dig in a little deeper into the code to see exactly when the service gets started, but I think I should be able to find it.
- Maybe only show the setting if more than one tag exists?
- Clean up root_preferences.xml and use strings from resource and not hard-coded ones.
- I think it would be nice to add a summary to the setting listing the "freezable" tags. What do you think?

I'm open to all kinds of suggestions. I'll try to follow your style but don't hesitate on telling me if there is something you don't like or if there is something that could be solved in a nicer/better way.

Again, thank you very much! :+1: 

Edit (20221003): add todo (root_preferences and strings)
Edit (20221003): add summary to setting

### CODE REVIEW

**Comment by juanitobananas** [comment]
> - It would be nice not to start the auto-freeze service at all (so that the notification isn't shown) if the launched apps aren't supposed to be frozen. I still have to dig in a little deeper into the code to see exactly when the service gets started, but I think I should be able to find it.

I might have managed to implement this in [4b92586](https://github.com/aistra0528/Hail/pull/43/commits/4b9258628005125fe0a264400bab09873c70eeda) :smile:

**Comment by juanitobananas** [comment]
> - I think it would be nice to add a summary to the setting listing the "freezable" tags. What do you think?

I went ahead and added it in commit [a171492](https://github.com/aistra0528/Hail/pull/43/commits/a1714928a349e310e26623e7b22b4a2e59852ba7).

This commit also adds a fail-safe mechanism while getting autoFreezeTags which could cause crashes, when a tag was deleted or renamed. It is more of a work-around than a real solution, as it doesn't track tag name changes. If a tag is renamed, it won't be auto-frozen anymore... Which isn't that bad, but isn't nice either.

I tried to follow the tab renaming logic but got a little lost. I'll give it another try at some point.

**Comment by juanitobananas** [comment]
Just rebased everything... And added a commit that removed some unnecessary non-null assertions. For my part, this is more or less complete. If you are willing to merge it, I could squash all (or at least some) commits if you wish.

I just took a quick look at the new whitelist feature, and I'm not sure the auto-freeze tags settings is that useful anymore. I still like it, but something similar could be achieved using the whitelist as is right now. Maybe an option to whitelist all apps in a tag would be nice...

Any thoughts?

**Comment by aistra0528** [comment]
Do you think it's a good idea to multi-select applications to add or remove from the whitelist?

**Comment by juanitobananas** [comment]
I think that would be a good thing, yes. But also not extremely important :smile:

I still like my auto-freeze-tags feature, but I think it's mostly because I just implemented it. I can achieve nearly the same thing with the new whitelisting feature.

Please do as you wish regarding this MR :blush:

**Pull request closed without merging**
